spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  application:
    name: user
  servlet:
    multipart:
      max-file-size: 100000MB
      max-request-size: 100000MB

server:
  port: 8081


